name: Blob storage website CI

permissions:
  contents: read
  checks: write
  id-token: write

on:
    push:
        branches: [ main ]

env:
  SA_NAME: ${{ vars.SA_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.SA_NAME }} --auth-mode login --overwrite -d '$web/contact' -s ./contact/
            az storage blob upload-batch --account-name ${{ env.SA_NAME }} --auth-mode login --overwrite -d '$web/swiruhack' -s ./swiruhack/ 

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubS3ContentDeployment
        role-session-name: KSCSC-GitHub-Deployment

    - name: Upload to S3 (Contact)
      run:
        aws s3 sync ./contact/ s3://${{ env.SA_BUCKET }}/contact/ --delete

    - name: Upload to S3 (Swiruhack)
      run: |
        aws s3 sync ./swiruhack/ s3://${{ env.SA_BUCKET }}/swiruhack/ --delete

  # DAST
  DastardlyScan:
    runs-on: ubuntu-latest
    steps:
    - name: Dastardly Scan Action
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://blog.kscsc.online'

    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/dastardly-report.xml'
        require_tests: true

