name: Blob storage website CI

permissions:
  contents: read
  checks: write
  id-token: write

on:
    push:
        branches: [ main ]

env:
  SA_NAME: ${{ vars.SA_NAME }}
  CDN_PROFILE_NAME: ${{ vars.CDN_PROFILE_NAME }}
  CDN_ENDPOINT_CONTACT: ${{ vars.CDN_ENDPOINT_CONTACT }}
  CDN_ENDPOINT_BLOG: ${{ vars.CDN_ENDPOINT_BLOG }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.SA_NAME }} --auth-mode login --overwrite -d '$web/contact' -s ./contact/
            az storage blob upload-batch --account-name ${{ env.SA_NAME }} --auth-mode login --overwrite -d '$web/swiruhack' -s ./swiruhack/ 
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()

  # DAST
    - name: Dastardly Scan Action
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://blog.kscsc.online'

    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/dastardly-report.xml'
        require_tests: true

